name:                KasperskyBase
version:             0.1.0.0
github:              "JustRoxy/KasperskyBase"
license:             BSD3
author:              "JustRoxy"
maintainer:          "https://github.com/JustRoxy/"
copyright:           "2020 JustRoxy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JustRoxy/KasperskyBase#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  KasperskyBase-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KasperskyBase

tests:
  KasperskyBase-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KasperskyBase
